feature/se-76
SE2-WS23/documentation pull request #81
Opened 2023-11-27 19:28 UTC by julix14

![image](https://github.com/SE2-WS23/documentation/assets/65715000/f7c8bfc4-72b9-4400-bbae-ce70ae34d978)

closes #76

2023-11-27 21:05 UTC, Chrissydrx requested changes

2023-11-27 21:05 UTC, Chrissydrx commented on api-models/user.yml
> +          description: lastname of the user.
```suggestion
          description: Lastname of the user.
```

2023-11-27 21:05 UTC, Chrissydrx commented on api-models/user.yml
> +      description: Delete existing user details such as name, email, password, role.
Rather delete the user entirely?

2023-11-27 21:05 UTC, Chrissydrx commented on api-models/user.yml
> +          description: Array of tag IDs to fetch a subset of users
```suggestion
          description: Array of user IDs to fetch a subset of users
```

2023-11-27 21:05 UTC, Chrissydrx commented on api-models/user.yml
> +      description: Create a new user with email, password, and role.
```suggestion
      description: Create a new user with firstname, lastname, email, password, and role.
```

2023-11-27 21:05 UTC, Chrissydrx commented on api-models/user.yml
> +      description: Update existing user details such as name, email, password, role.
```suggestion
      description: Update existing user details such as firstname, lastname, email, password, role.
```

2023-11-27 21:43 UTC, julix14 commented on api-models/user.yml
> +      description: Delete existing user details such as name, email, password, role.
True, chatgpt is stupid

2023-12-01 15:27 UTC, Chrissydrx approved these changes

2023-12-01 15:27 UTC, merged